<a href="https://colab.research.google.com/github/Njeon3091/AICE_study/blob/main/epass_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import lightgbm as gbm

In [10]:
estate_df1 = pd.read_csv('2_real_estate_valuation_1.csv')
estate_df2 = pd.read_csv('2_real_estate_valuation_2.csv')

In [12]:
estate_df1.head()

   number region  area_sqm  num_rooms  num_bathrooms  building_age
0       1     서초       105        4.0            3.0          12.0
1       2     서초       105        2.0            3.0          13.0
2       3     강남       128        1.0            2.0          18.0
3       4     강남       137        2.0            1.0          13.0
4       5     서초       115        1.0            1.0          38.0

In [13]:
estate_df2.head()

,number,building_material,parking_spaces,subway_stations_1km,amenities_500m,school_score,price_eok
0,1,목조,1.0,1.0,11,7,29.7
1,2,목조,2.0,3.0,2,3,29.6
2,3,벽돌,2.0,NaN,11,9,30.3
3,4,벽돌,2.0,0.0,5,3,29.1
4,5,철근콘크리트,1.0,3.0,10,4,26.4

In [17]:
estate = estate_df1.merge(estate_df2, on = 'number', how = 'inner')

In [18]:
estate.head()

,number,region,area_sqm,num_rooms,num_bathrooms,building_age,building_material,parking_spaces,subway_stations_1km,amenities_500m,school_score,price_eok
0,1,서초,105,4.0,3.0,12.0,목조,1.0,1.0,11,7,29.7
1,2,서초,105,2.0,3.0,13.0,목조,2.0,3.0,2,3,29.6
2,3,강남,128,1.0,2.0,18.0,벽돌,2.0,NaN,11,9,30.3
3,4,강남,137,2.0,1.0,13.0,벽돌,2.0,0.0,5,3,29.1
4,5,서초,115,1.0,1.0,38.0,철근콘크리트,1.0,3.0,10,4,26.4